
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const App = lazy(() => import("./pages/App.tsx"));
const CommunityForumPage = lazy(() => import("./pages/CommunityForumPage.tsx"));
const CommunityHubPage = lazy(() => import("./pages/CommunityHubPage.tsx"));
const CreateCommunityPage = lazy(() => import("./pages/CreateCommunityPage.tsx"));
const Landinscape = lazy(() => import("./pages/Landinscape.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const LoginPage = lazy(() => import("./pages/LoginPage.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const RegisterPage = lazy(() => import("./pages/RegisterPage.tsx"));
const TestCommunityApiPage = lazy(() => import("./pages/TestCommunityApiPage.tsx"));
const TopicDetailPage = lazy(() => import("./pages/TopicDetailPage.tsx"));
const UserDashboardPage = lazy(() => import("./pages/UserDashboardPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <UserGuard><App /></UserGuard>},
	{ path: "/community-forum-page", element: <UserGuard><CommunityForumPage /></UserGuard>},
	{ path: "/communityforumpage", element: <UserGuard><CommunityForumPage /></UserGuard>},
	{ path: "/community-hub-page", element: <UserGuard><CommunityHubPage /></UserGuard>},
	{ path: "/communityhubpage", element: <UserGuard><CommunityHubPage /></UserGuard>},
	{ path: "/create-community-page", element: <UserGuard><CreateCommunityPage /></UserGuard>},
	{ path: "/createcommunitypage", element: <UserGuard><CreateCommunityPage /></UserGuard>},
	{ path: "/landinscape", element: <Landinscape />},
	{ path: "/login", element: <Login />},
	{ path: "/login-page", element: <UserGuard><LoginPage /></UserGuard>},
	{ path: "/loginpage", element: <UserGuard><LoginPage /></UserGuard>},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/register-page", element: <UserGuard><RegisterPage /></UserGuard>},
	{ path: "/registerpage", element: <UserGuard><RegisterPage /></UserGuard>},
	{ path: "/test-community-api-page", element: <UserGuard><TestCommunityApiPage /></UserGuard>},
	{ path: "/testcommunityapipage", element: <UserGuard><TestCommunityApiPage /></UserGuard>},
	{ path: "/topic-detail-page", element: <UserGuard><TopicDetailPage /></UserGuard>},
	{ path: "/topicdetailpage", element: <UserGuard><TopicDetailPage /></UserGuard>},
	{ path: "/user-dashboard-page", element: <UserGuard><UserDashboardPage /></UserGuard>},
	{ path: "/userdashboardpage", element: <UserGuard><UserDashboardPage /></UserGuard>},

];
